version: '3.8'

services:
    # Laravel App Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-tasks-app
        ports:
            - "8001:8001"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=tasks
            - DB_USERNAME=root


    # MySQL Database Service
    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: tasks
            MYSQL_USER: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
        driver: local
